### ISSUE TITLE
Can't build against GDAL 2.4 - update requirements-dev?

### ISSUE THREAD

**Issue by bradh** [geopython/pygeoapi#146]
```
    running build_ext
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python3.7m -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include -c gdal_python_cxx11_test.cpp -o gdal_python_cxx11_test.o
    building 'osgeo._gdal' extension
    creating build/temp.linux-x86_64-3.7
    creating build/temp.linux-x86_64-3.7/extensions
    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I../../port -I../../gcore -I../../alg -I../../ogr/ -I../../ogr/ogrsf_frmts -I../../gnm -I../../apps -I/usr/include/python3.7m -I/usr/lib/python3/dist-packages/numpy/core/include -I/usr/include -c extensions/gdal_wrap.cpp -o build/temp.linux-x86_64-3.7/extensions/gdal_wrap.o -I/usr/include/gdal
    extensions/gdal_wrap.cpp: In function ‘OSRSpatialReferenceShadow* GDALDatasetShadow_GetSpatialRef(GDALDatasetShadow*)’:
    extensions/gdal_wrap.cpp:4672:32: error: ‘GDALGetSpatialRef’ was not declared in this scope
         OGRSpatialReferenceH ref = GDALGetSpatialRef(self);
                                    ^~~~~~~~~~~~~~~~~
```

Looks like that is a GDAL 3.0 thing.

**Comment by justb4** [comment]
@bradh Hmm, yes I think as the [Dockerfile](https://github.com/geopython/pygeoapi/blob/master/Dockerfile) builds with GDAL 2.4 (`libgdal20 amd64 2.4.0+dfsg-1+b1`) ok (on vanilla Debian Buster). On what OS/version are you building, possibly with custom GDAL (3) install? Possibly requirement should become: `GDAL>=2.2,<3.0`?

**Comment by bradh** [comment]
It failed on ubuntu 19.04, with libgdal-dev installed. I manually built GDAL 3.0 and it worked OK.
I did see pip (pip3 in my case) bring in a python GDAL3.0 package.

**Comment by justb4** [comment]
Ok, GDAL pinned to `GDAL>=2.2,<3.0`. Docker build (Debian Buster) btw uses native Deb packages `libgdal20` and `python3-gdal` (GDAL 2.4.0). That satisfies the `pip` `requirements-dev.txt`. After much experimentation this appeared the easiest/quickest, no wheel compilation nor GDAL `include` PATHs etc required.

**Comment by bradh** [comment]
This looks like it can be closed.
