### ISSUE TITLE
Latest pygeoapi Docker image fails

### ISSUE THREAD

**Issue by justb4** [geopython/pygeoapi#547]
**Description**
Latest pygeoapi Docker image fails on https://demo.pygeoapi.io/

**Steps to Reproduce**
go to https://demo.pygeoapi.io/ 
try any of the latest endpoints, master covid cite
any of these fails

**Expected behavior**
service pages

**Screenshots/Tracebacks**
na

**Environment**
 - OS: any
 - Python version: 3
 - pygeoapi version: master

**Additional context
Happened after #542 and #544 went in....

**Comment by justb4** [comment]
Somehow pygeoapi is not accepting connections. When putting Traefik proxy frontend into DEBUG mode:

and then `docker logs --follow traefik`

```
time="2020-09-29T09:04:57Z" level=debug msg="Upstream ResponseWriter of type *pipelining.writerWithoutCloseNotify does not implement http.CloseNotifier. Returning dummy channel."
time="2020-09-29T09:04:57Z" level=debug msg="'502 Bad Gateway' caused by: read tcp 172.18.0.4:55656->172.18.0.5:80: read: connection reset by peer"
```
172.18.0.5:80 is the pygeoapi (master) Docker Container on demo.pygeoapi.io.

and then `docker logs --follow pygeoapi_master` on startup shows no errors, only this strange warning **greenlet.greenlet size changed** (?): This hints strongly at #545 (*gunicorn doesn't work with greenlet 0.4.17*)

```
START /entrypoint.sh
Trying to generate openapi.yml
openapi.yml generated continue to pygeoapi
Start gunicorn name=pygeoapi on 0.0.0.0:80 with 4 workers and SCRIPT_NAME=/master
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
.
.
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
<frozen importlib._bootstrap>:219: RuntimeWarning: greenlet.greenlet size changed, may indicate binary incompatibility. Expected 144 from C header, got 152 from PyObject
[2020-09-29 09:03:29 +0000] [1] [INFO] Starting gunicorn 20.0.4
[2020-09-29 09:03:29 +0000] [1] [INFO] Listening at: http://0.0.0.0:80 (1)
[2020-09-29 09:03:29 +0000] [1] [INFO] Using worker: gevent
[2020-09-29 09:03:29 +0000] [21] [INFO] Booting worker with pid: 21
.
[2020-09-29 09:09:36 +0000] [27] [INFO] Booting worker with pid: 27
```

**Comment by justb4** [comment]
Can be closed, dup of #545.
